version: "3"

services:

  frontend:
    build: ./frontend
    container_name: frontend_container
    working_dir: /app
    ports: ["8080:8080"]
    command: bash -c "npm install && npm run start-test"

  query-service:
    image: clojure:openjdk-14-lein
    container_name: query-service-container
    ports: ["3000:3000"]
    command: tail -f /dev/null
    working_dir: /app
    command: lein with-profile test run
    volumes:
      - query-service-app:/app

  janusgraph:
    image: janusgraph/janusgraph:latest
    container_name: janusgraph-default
    ports: ["8182:8182"]

  holochain:
    build: ./holochain
    container_name: holochain-container
    ports: ["8888:8888"]
    command: bash -c ". /home/docker/.nix-profile/etc/profile.d/nix.sh \
                         && nix-shell http://holochain.love --command \
                            \"hc package && holochain -c in-memory-instance-conductor-config.toml\""
    volumes:
      - holochain-app:/holochain

volumes:
  janusgraph-default-data:
  holochain-app:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .$PWD/holochain/app
  query-service-app:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .$PWD/query-service
